version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    
    steps:
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      
      - checkout
      - run:
          command: |
            git submodule init
            git submodule update
      - run:
          command: |
            go test -v ./tests/... -test.short
            go test -v ./state/...

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
